name: dashboard
description: Flutter admin dashboard app.
publish_to: "none"
version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  google_fonts: ^2.1.0
  fl_chart: ^0.36.1
  auto_route: ^2.2.0
  font_awesome_flutter: ^9.1.0
  multi_select_flutter: ^4.0.0

  #Firebase Dependencies
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  auto_route_generator: ^2.1.0
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
