name: dashboard
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^1.0.0-beta.6

dev_dependencies:
  auto_route_generator: ^1.0.0-beta.6
  build_runner:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
